spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
    driverclassname: com.mysql.cj.jdbc.Driver
edmpscheduler:
  remoteHost: "10.8.9.100"
  userName: "admin"
  remotePath: "/ctrl/abc/incomingfile"
  privateKey: "/home/admin/.ssh/id_rsa_test"
  knownHost: "/home/admin/.ssh/known_hosts"
  passPhrase: "changeit"

